name: "Terraform Quality Check"

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    
    # Rozwiązanie problemu deprecjacji Node.js 20
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

    steps:
      - name: Checkout Code
        # Aktualizacja do v5 (wspiera Node.js 24)
        uses: actions/checkout@v5

      - name: Setup Terraform
        # Aktualizacja do v4 (wspiera Node.js 24)
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.7.0"

      - name: 1. Sprawdzenie formatowania (fmt)
        run: terraform fmt -check
        # Zwróci exit code 3, jeśli kod wymaga poprawki (fmt)

      - name: 2. Inicjalizacja (Init)
        # Używamy -backend=false, bo w CI sprawdzamy tylko kod, nie łączymy się ze stanem (State)
        run: terraform init -backend=false

      - name: 3. Walidacja logiczna (Validate)
        run: terraform validate

      - name: 4. Skanowanie bezpieczeństwa (tfsec)
        uses: aquasecurity/tfsec-action@v1.0.0
    